name: Unity EditMode Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projectPath:
          - .
        testMode:
          - EditMode

    steps:
      # 1. Checkout your repo
      - uses: actions/checkout@v3
        with: 
          lfs: true

      # 3. Run EditMode tests via CLI
      - uses: game-ci/unity-test-runner@v4
        id: tests
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.testMode }} Test Results

      # 4. Upload raw test results as artifact (optional)
      - name: Upload Test Results Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Test-Results
          path: ${{ github.workspace }}/TestResults/test_results.xml

      # 5. Parse JUnit XML and fail workflow if any test failed
      - name: Report Unity Test Results
        uses: dorny/test-reporter@v1
        with:
          name: Unity EditMode Tests
          path: ${{ github.workspace }}/TestResults/test_results.xml
          reporter: junit
          fail-on-error: true