name: Asteroid Destroyer Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projectPath:
          - .
        testMode:
          - EditMode

    steps:
      # 1. Checkout your repo
      - name: Checkout repo
        uses: actions/checkout@v3
        with: 
          lfs: true

      # 2. Run EditMode tests via CLI
      - name: Run EditMode tests via CLI
        uses: game-ci/unity-test-runner@v4
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.testMode }} Test Results

      # 3. Upload raw test results as artifact (optional)
      - name: Upload Test Results Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Test-Results
          path: ${{ github.workspace }}/EditMode-artifacts/editmode-results.xml